title: Sports HQ
description: Find your game. Build your team.
url: https://www.sportshq.io

plugins:
  - jekyll-sitemap

include:
  - .well-known

exclude:
  - node_modules
  - src
  - docs
  - test
  - _site
  - docker-compose.yml
  - package.json
  - package-lock.json
  - tailwind.config.js
  - Gemfile
  - Gemfile.lock
  - "README*.md"
